module "eso_iam_roles" {
  source = "../../modules/external-secrets-operator"

  environment = var.environment

  name_prefix = local.name_prefix

  oidc_provider_arn            = aws_iam_openid_connect_provider.cluster.arn
  cluster_identity_oidc_issuer = split("https://", aws_eks_cluster.cluster.identity[0].oidc[0].issuer)[1]

  # Kubernetes namespaces enrolled in External Secrets integration.
  # Each name in this list will get an autogenerated IAM role with RO
  # access to a subset of external secrets.
  namespaces = toset([
    "asset-control",
    "dare-web",
    "data-platform",
    "exchanges",
    "flux-alerting",
    "insights",
    "kube-system",
    "kubernetes-training",
    "newrelic",
    "operations",
    "performr",
    "power-trading",
    "rad",
    "scorecard",
    "trading",
    "trainr",
    "weave-gitops"
  ])
}
